boolean nodes and tests
flojoy-ai/blocks pull request #11
Opened 2023-10-26 22:05 UTC by Jin1L

2023-10-27 20:40 UTC, itsjoeoui submitted a review, later dismissed

2023-10-27 20:40 UTC, itsjoeoui commented on blocks/DATA/GENERATION/SIMULATIONS/BOOLEAN/BOOLEAN.py
> +    status : True
status : bool, default=True

2023-10-30 14:13 UTC, dstrande requested changes

2023-10-30 14:13 UTC, dstrande commented on blocks/DATA/GENERATION/SIMULATIONS/BOOLEAN/BOOLEAN.py
> +    """The MATRIX node takes two arguments, 'row' and 'col', as input.
Update the docstring

2023-10-30 14:13 UTC, dstrande commented on blocks/DATA/GENERATION/SIMULATIONS/VECTOR/VECTOR.py
> +    elements: str = "", elements_type: Literal["boolean", "integer"] = "boolean"
Should this be boolean and numeric (i.e float and integer)

2023-10-30 14:13 UTC, dstrande commented on blocks/ETL/TRANSFORM/TYPE_CASTING/VECTOR_2_SCALAR/VECTOR_2_SCALAR.py
> +
Add a line saying how the scalar is calculated. Sum or whatever

2023-10-31 20:37 UTC, dstrande requested changes
Hey sorry two more changes:

1. Remove the first couple words in the docstring so its just: `Takes two boolean ...`
2. Change all `node` references to `block` which is what we changed the name to

2023-10-31 20:37 UTC, dstrande commented on blocks/CONTROL_FLOW/LOGICAL_OPERATORS/AND/AND.py
> +    """The AND node takes two boolean data type and computs logical AND operation on them.
Remove the first two works on all blocks and change `node` to `block` for all blocks

2023-11-06 14:47 UTC, dstrande approved these changes

2023-11-06 14:49 UTC, merged