Move keyframes
flojoy-ai/blocks pull request #12
Opened 2023-10-27 10:10 UTC by TheBigSasha

2023-10-27 18:23 UTC, itsjoeoui commented
@TheBigSasha not sure if I understand the issue with log, but you can build locally with `pnpm build` which will give you the same log

2023-11-16 04:32 UTC, jingxiangmo requested changes
Remove .idea

2023-11-16 04:35 UTC, jingxiangmo submitted a review, later dismissed

2023-11-17 16:23 UTC, JeffDotPng reviewed
Almost exclusively docstring things, also a couple broken imports i believe need to be fixed

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/CALCULATE_CIRCLE_MOVE/CALCULATE_CIRCLE_MOVE.py
> +    point_duration: Optional[int] = 500,
There's no need to specify optional for all of these, having a default value is enough

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/CALCULATE_CIRCLE_MOVE/CALCULATE_CIRCLE_MOVE.py
> +from PYTHON.utils.mecademic_state.mecademic_calculations import getCirclePositions
I believe this name needs to be updated to snake_case

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/CALCULATE_CIRCLE_MOVE/CALCULATE_CIRCLE_MOVE.py
> +        The duration of each point in milliseconds. If not specified, the default value of 500 is used.
```suggestion
    center_X : float
        The X coordinate of the center of the circle. If not specified, the default value of 0.0 is used.
    center_Y : float
        The Y coordinate of the center of the circle. If not specified, the default value of 0.0 is used.
    center_Z : float
        The Z coordinate of the center of the circle. If not specified, the default value of 0.0 is used.
    radius : float
        The radius of the circle. If not specified, the default value of 0.0 is used.
    revolutions : float
        The number of revolutions to make. If not specified, the default value of 1.0 is used.
    point_duration : int
        The duration of each point in milliseconds. If not specified, the default value of 500 is used.
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/CALCULATE_CIRCLE_MOVE/CALCULATE_CIRCLE_MOVE.py
> +    dataframe
```suggestion
    DataFrame
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/DELAY/DELAY.py
> +    ------
```suggestion
    Parameters
    ----------
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/DISCONNECT/DISCONNECT.py
> +    ------
```suggestion
    Parameters
    ----------
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/HOME/HOME.py
> +    ------
```suggestion
    Parameters
    ----------
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_CIRCLE/MOVE_CIRCLE.py
> +    revolutions: Optional[float] = 1.0,
```suggestion
    radius: float = 0.0,
    revolutions: float = 1.0,
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_CIRCLE/MOVE_CIRCLE.py
> +        The number of revolutions to make. If not specified, the default value of 1.0 is used.
```suggestion
    Parameters
    ----------
    ip_address: TextBlob
        The IP address of the robot arm.
    radius: float
        The radius of the circle. If not specified, the default value of 0.0 is used.
    revolutions: float
        The number of revolutions to make. If not specified, the default value of 1.0 is used.
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_CIRCLE/MOVE_CIRCLE.py
> +    ip_address
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/HOME/HOME.py
> +    ip_address: TextBlob
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/DELAY/DELAY.py
> +    ip_address: TextBlob
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/CONNECT/CONNECT.py
>      String
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_JOINT/MOVE_JOINT.py
> +    ip_address
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_KEYFRAMES/MOVE_KEYFRAMES.py
> +    ------
```suggestion
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_KEYFRAMES/MOVE_KEYFRAMES.py
> +    ip_address
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_KEYFRAMES/MOVE_KEYFRAMES.py
> +from PYTHON.utils.mecademic_state.mecademic_calculations import calculateLimitingMaxVel
Seems like this should be updated to the snake_case name

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_KEYFRAMES_LIN/MOVE_KEYFRAMES_LIN.py
> +    ------
```suggestion
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_KEYFRAMES_LIN/MOVE_KEYFRAMES_LIN.py
> +from PYTHON.utils.mecademic_state.mecademic_calculations import calculateLimitingMaxVel
update to snake_case

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_LIN/MOVE_LIN.py
> +    ip_address: TextBlob
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_JOINT/MOVE_JOINT.py
> +        The IP address of the robot arm.
We don't do the whole separate Inputs and Parameters sections thing anymore, you can just put it all under "Parameters"

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_LIN/MOVE_LIN.py
> +        The IP address of the robot arm.
Put under parameters

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_LIN_REL_TRF/MOVE_LIN_REL_TRF.py
> +    gamma: Optional[float] = 0,
```suggestion
    alpha: float = 0,
    beta: float = 0,
    gamma: float = 0,
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_LIN_REL_TRF/MOVE_LIN_REL_TRF.py
> +        The gamma coordinate (rotation in radians about the z axis) of the position to move to.
```suggestion
    alpha : float
        The alpha coordinate (rotation in radians about the x axis) of the position to move to.
    beta : float
        The beta coordinate   (rotation in radians about the y axis) of the position to move to.
    gamma : float
        The gamma coordinate (rotation in radians about the z axis) of the position to move to.
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_LIN_REL_TRF/MOVE_LIN_REL_TRF.py
> +    ip_address
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_POSE/MOVE_POSE.py
> +        The IP address of the robot arm.
Put this under Parameters

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/MOVE_POSE/MOVE_POSE.py
> +    ip_address
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_BLENDING/SET_BLENDING.py
> +        The IP address of the robot arm.
Put this under Parameters

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_BLENDING/SET_BLENDING.py
> +def SET_BLENDING(ip_address: TextBlob, blending: Optional[float] = 0.0) -> TextBlob:
```suggestion
def SET_BLENDING(ip_address: TextBlob, blending: float = 0.0) -> TextBlob:
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_BLENDING/SET_BLENDING.py
> +    blending: Optional[float]
```suggestion
    blending: float
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_BLENDING/SET_BLENDING.py
> +    ip_address
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_CART_LIN_VEL/SET_CART_LIN_VEL.py
>          The IP address of the robot arm.
Put under Parameters

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_JOINT_VEL/SET_JOINT_VEL.py
> +        The IP address of the robot arm.
Put under Parameters

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_JOINT_VEL/SET_JOINT_VEL.py
> +    ip_address: TextBlob
```suggestion
    TextBlob
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_TRF/SET_TRF.py
> +    rf_g: Optional[float] = 0.0,
```suggestion
    rf_x: float = 0.0,
    rf_y: float = 0.0,
    rf_z: float = 0.0,
    rf_a: float = 0.0,
    rf_b: float = 0.0,
    rf_g: float = 0.0,
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_TRF/SET_TRF.py
> +        The gamma angle of the reference plane. If not specified, the default value of 0.0 is used.
```suggestion
    rf_x: float
        The X coordinate of the reference plane. If not specified, the default value of 0.0 is used.
    rf_y: float
        The Y coordinate of the reference plane. If not specified, the default value of 0.0 is used.
    rf_z: float
        The Z coordinate of the reference plane. If not specified, the default value of 0.0 is used.
    rf_a: float
        The alpha angle of the reference plane. If not specified, the default value of 0.0 is used.
    rf_b: float
        The beta angle of the reference plane. If not specified, the default value of 0.0 is used.
    rf_g: float
        The gamma angle of the reference plane. If not specified, the default value of 0.0 is used.
```

2023-11-17 16:23 UTC, JeffDotPng commented on blocks/HARDWARE/ROBOTICS/ARMS/MECADEMIC/SET_TRF/SET_TRF.py
> +         The IP address of the robot arm.
```suggestion
    TextBlob
         The IP address of the robot arm.
```

2023-11-17 19:05 UTC, jingxiangmo commented
Resolved all PR suggestions and conversations

2023-11-20 20:22 UTC, JeffDotPng approved these changes

2023-11-20 20:23 UTC, merged